// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18TgoHR4MZjEs_oBngnQ3f5UlrC4ylCY',
    appId: '1:676055554223:web:ea3cddd30eabb36f031c5a',
    messagingSenderId: '676055554223',
    projectId: 'chidera-flutter-project',
    authDomain: 'chidera-flutter-project.firebaseapp.com',
    storageBucket: 'chidera-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SQxtGZOLQdTA8nKYVCXOnhdkDKB9ZIw',
    appId: '1:676055554223:android:04f7fbc20ddea287031c5a',
    messagingSenderId: '676055554223',
    projectId: 'chidera-flutter-project',
    storageBucket: 'chidera-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMWzmbhoFgzpKWULrKyIZdQ9vN-jxNKaI',
    appId: '1:676055554223:ios:0dc431a683010448031c5a',
    messagingSenderId: '676055554223',
    projectId: 'chidera-flutter-project',
    storageBucket: 'chidera-flutter-project.appspot.com',
    iosBundleId: 'com.example.truckhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMWzmbhoFgzpKWULrKyIZdQ9vN-jxNKaI',
    appId: '1:676055554223:ios:cf791e3f03706cda031c5a',
    messagingSenderId: '676055554223',
    projectId: 'chidera-flutter-project',
    storageBucket: 'chidera-flutter-project.appspot.com',
    iosBundleId: 'com.example.truckhub.RunnerTests',
  );
}
